language: python

python:
  - "3.12"

services:
  - postgresql

env:
  global:
    - FLASK_ENV=testing
    - DATABASE_URL=postgresql://postgres@localhost/sultan_test
    - SPACES_KEY=your_spaces_key
    - SPACES_SECRET=your_spaces_secret
    - SPACES_REGION=fra1
    - SPACES_BUCKET=sultan-prints
    - SPACES_CDN_DOMAIN=https://sultan-prints.fra1.cdn.digitaloceanspaces.com

before_install:
  - pip install --upgrade pip

install:
  - pip install -r requirements.txt

before_script:
  # إنشاء قاعدة بيانات PostgreSQL للاختبار
  - psql -c "CREATE DATABASE sultan_test;" -U postgres
  # تأكيد إعداد Alembic للهجرة
  - alembic upgrade head

script:
  # لا يوجد اختبارات حالياً، لكن نفحص إذا wsgi.py يعمل بدون مشاكل
  - python -m py_compile wsgi.py

after_success:
  - echo "✅ المشروع تم تجهيزه بنجاح على Travis CI (لا يوجد اختبارات حالياً)"
