# render.yaml
# Blueprint for deploying the T-shirt Shop on Render

databases:
  - name: tshirt_store_db
    databaseName: tshirt_store_db
    user: tshirt_shop_user
    plan: free # Use 'starter' or other paid plans for production
    region: frankfurt # Choose a region close to you

services:
  - type: web
    name: tshirt-shop-web
    runtime: python
    region: frankfurt # Must be the same region as the database
    plan: free # Use 'starter' or other paid plans for production
    buildCommand: "./build.sh"
    startCommand: "gunicorn wsgi:app"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: tshirt_store_db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true # Automatically generates a secure secret key
      - key: PYTHON_VERSION
        value: 3.11.12 # Match your local development version
      - key: FLASK_APP
        value: "wsgi:app"
      - key: FLASK_ENV
        value: production
      # --- User-provided Environment Variables ---
      # You MUST set these secrets in the Render dashboard under your service's 'Environment' section
      - key: ADMIN_EMAIL
        value: "admin@example.com"
      - key: ADMIN_PASSWORD
        sync: false
      - key: MAIL_USERNAME
        value: "your-smtp-username@gmail.com"
      - key: MAIL_PASSWORD
        sync: false
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: STRIPE_PUBLISHABLE_KEY
        sync: false 