"""Add custom_designs table

Revision ID: 03e18086b320
Revises: f7dbd6731a0d
Create Date: 2025-06-15 21:21:31.606761

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '03e18086b320'
down_revision = 'f7dbd6731a0d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('custom_designs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_name', sa.String(length=120), nullable=True),
    sa.Column('customer_email', sa.String(length=120), nullable=True),
    sa.Column('customer_phone', sa.String(length=32), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('governorate_id', sa.Integer(), nullable=True),
    sa.Column('design_file', sa.String(length=255), nullable=False),
    sa.Column('design_description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('archived', sa.Boolean(), nullable=True),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['governorate_id'], ['governorates.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('discounts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_discounts_code'))

    op.drop_table('discounts')
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('archived', sa.Boolean(), nullable=True))
        batch_op.drop_column('discount_amount')
        batch_op.drop_column('discount_code')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('discount_code', mysql.VARCHAR(length=20), nullable=True))
        batch_op.add_column(sa.Column('discount_amount', mysql.FLOAT(), nullable=True))
        batch_op.drop_column('archived')

    op.create_table('discounts',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('code', mysql.VARCHAR(length=32), nullable=False),
    sa.Column('is_active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('type', mysql.VARCHAR(length=16), nullable=False),
    sa.Column('value', mysql.FLOAT(), nullable=False),
    sa.Column('min_purchase', mysql.FLOAT(), nullable=True),
    sa.Column('max_discount', mysql.FLOAT(), nullable=True),
    sa.Column('start_date', mysql.DATETIME(), nullable=False),
    sa.Column('end_date', mysql.DATETIME(), nullable=False),
    sa.Column('usage_limit', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('times_used', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('discounts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_discounts_code'), ['code'], unique=True)

    op.drop_table('custom_designs')
    # ### end Alembic commands ###
