"""add governorate_name and delivery_fee to order

Revision ID: 04bf5130a3fd
Revises: 6a6bdfc1276c
Create Date: 2025-06-12 14:48:38.345231

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04bf5130a3fd'
down_revision = '6a6bdfc1276c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('governorates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('delivery_fee', sa.Float(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('governorate_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('delivery_fee', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_column('delivery_fee')
        batch_op.drop_column('governorate_name')

    op.drop_table('governorates')
    # ### end Alembic commands ###
