"""Add created_at to Discount model

Revision ID: 240f7c81a846
Revises: f8c6c25e8313
Create Date: 2025-06-07 20:19:17.015172

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '240f7c81a846'
down_revision = 'f8c6c25e8313'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('discounts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('discounts', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
