"""Add discount fields to Order model

Revision ID: 6a6bdfc1276c
Revises: f3be5290b239
Create Date: 2025-06-09 16:39:02.814351

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a6bdfc1276c'
down_revision = 'f3be5290b239'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('discount_code', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('discount_amount', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_column('discount_amount')
        batch_op.drop_column('discount_code')

    # ### end Alembic commands ###
