"""add governorate_id and delivery_fee to orders

Revision ID: a9a399946780
Revises: 94e2d4680319
Create Date: 2025-06-13 17:03:53.385248

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a9a399946780'
down_revision = '94e2d4680319'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order_product',
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('order_id', 'product_id')
    )
    with op.batch_alter_table('governorates', schema=None) as batch_op:
        batch_op.drop_column('created_at')
        batch_op.drop_column('updated_at')
        batch_op.drop_column('is_active')

    # إصلاح مشكلة القيم الفارغة قبل جعل العمود NOT NULL
    op.execute("UPDATE orders SET delivery_fee = 0 WHERE delivery_fee IS NULL;")
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('governorate_id', sa.Integer(), nullable=True))
        batch_op.alter_column('delivery_fee',
               existing_type=mysql.FLOAT(),
               nullable=False)
        batch_op.create_foreign_key(None, 'governorates', ['governorate_id'], ['id'])
        batch_op.drop_column('governorate_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('governorate_name', mysql.VARCHAR(length=100), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('delivery_fee',
               existing_type=mysql.FLOAT(),
               nullable=True)
        batch_op.drop_column('governorate_id')

    with op.batch_alter_table('governorates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('updated_at', mysql.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('created_at', mysql.DATETIME(), nullable=True))

    op.drop_table('order_product')
    # ### end Alembic commands ###
