"""add promo_code_id column to orders

Revision ID: add_promo_code_id_to_orders
Revises: add_promocodes_table
Create Date: 2025-06-16 20:40:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'add_promo_code_id_to_orders'
down_revision = 'add_promocodes_table'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # التحقق من وجود العمود أولاً
    connection = op.get_bind()
    inspector = sa.inspect(connection)
    columns = [col['name'] for col in inspector.get_columns('orders')]
    
    if 'promo_code_id' not in columns:
        # إضافة عمود promo_code_id كـ nullable
        op.add_column('orders', sa.Column('promo_code_id', sa.Integer(), nullable=True))
        
        # إضافة foreign key constraint إذا كان جدول promocodes موجود
        try:
            op.create_foreign_key(None, 'orders', 'promocodes', ['promo_code_id'], ['id'])
        except Exception:
            # تجاهل الخطأ إذا لم يكن جدول promocodes موجود بعد
            pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    try:
        op.drop_constraint(None, 'orders', type_='foreignkey')
    except Exception:
        pass
    op.drop_column('orders', 'promo_code_id')
    # ### end Alembic commands ### 