"""add final_amount column to orders

Revision ID: add_final_amount_column_to_orders
Revises: add_archived_column_to_orders
Create Date: 2025-06-16 20:16:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'add_final_amount_column_to_orders'
down_revision = 'add_archived_column_to_orders'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # إضافة العمود كـ nullable أولاً
    op.add_column('orders', sa.Column('final_amount', sa.Float(), nullable=True))
    
    # تحديث القيم الموجودة
    op.execute("UPDATE orders SET final_amount = total_amount - discount_amount WHERE final_amount IS NULL")
    
    # جعل العمود NOT NULL
    op.alter_column('orders', 'final_amount', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'final_amount')
    # ### end Alembic commands ### 