"""Re-create discount table with correct definition

Revision ID: f3be5290b239
Revises: 79b9468f9caf
Create Date: 2025-06-09 15:51:39.749917

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f3be5290b239'
down_revision = '79b9468f9caf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('discounts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('value', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('min_purchase', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('max_discount', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('start_date', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('end_date', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('usage_limit', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('times_used', sa.Integer(), nullable=True))
        batch_op.alter_column('code',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.String(length=20),
               existing_nullable=False)
        batch_op.drop_column('percentage')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('discounts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('percentage', mysql.FLOAT(), nullable=False))
        batch_op.alter_column('code',
               existing_type=sa.String(length=20),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=False)
        batch_op.drop_column('times_used')
        batch_op.drop_column('usage_limit')
        batch_op.drop_column('end_date')
        batch_op.drop_column('start_date')
        batch_op.drop_column('max_discount')
        batch_op.drop_column('min_purchase')
        batch_op.drop_column('value')
        batch_op.drop_column('type')

    # ### end Alembic commands ###
