"""rebuild discounts table

Revision ID: f7dbd6731a0d
Revises: a9a399946780
Create Date: 2025-06-15 02:51:45.712157

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f7dbd6731a0d'
down_revision = 'a9a399946780'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('discounts', schema=None) as batch_op:
        batch_op.alter_column('code',
               existing_type=mysql.VARCHAR(length=20),
               type_=sa.String(length=32),
               existing_nullable=False)
        batch_op.alter_column('type',
               existing_type=mysql.VARCHAR(length=20),
               type_=sa.String(length=16),
               existing_nullable=False)
        batch_op.drop_index(batch_op.f('code'))
        batch_op.create_index(batch_op.f('ix_discounts_code'), ['code'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('discounts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_discounts_code'))
        batch_op.create_index(batch_op.f('code'), ['code'], unique=True)
        batch_op.alter_column('type',
               existing_type=sa.String(length=16),
               type_=mysql.VARCHAR(length=20),
               existing_nullable=False)
        batch_op.alter_column('code',
               existing_type=sa.String(length=32),
               type_=mysql.VARCHAR(length=20),
               existing_nullable=False)

    # ### end Alembic commands ###
