name: E2E Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  playwright:
    name: 'Playwright Tests'
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Build and run Docker container
        env:
          FLASK_ENV: "testing"
          SECRET_KEY: "test-secret-key"
          DATABASE_URL: "sqlite:///test.db"
          ADMIN_EMAIL: "admin@test.com"
          ADMIN_PASSWORD: "password"
          SESSION_COOKIE_SECURE: "False"
          MAILERLITE_API_KEY: "dummy-key"
          MAIL_DEFAULT_SENDER: "sender@test.com"
          SPACES_KEY: "dummy"
          SPACES_SECRET: "dummy"
          SPACES_BUCKET_NAME: "dummy"
          SPACES_REGION: "dummy"
          SPACES_CDN_DOMAIN: "dummy"
        run: |
          docker build --build-arg FLASK_ENV=${FLASK_ENV} \
                       --build-arg SECRET_KEY=${SECRET_KEY} \
                       --build-arg DATABASE_URL=${DATABASE_URL} \
                       --build-arg ADMIN_EMAIL=${ADMIN_EMAIL} \
                       --build-arg ADMIN_PASSWORD=${ADMIN_PASSWORD} \
                       --build-arg SESSION_COOKIE_SECURE=${SESSION_COOKIE_SECURE} \
                       --build-arg MAILERLITE_API_KEY=${MAILERLITE_API_KEY} \
                       --build-arg MAIL_DEFAULT_SENDER=${MAIL_DEFAULT_SENDER} \
                       --build-arg SPACES_KEY=${SPACES_KEY} \
                       --build-arg SPACES_SECRET=${SPACES_SECRET} \
                       --build-arg SPACES_BUCKET_NAME=${SPACES_BUCKET_NAME} \
                       --build-arg SPACES_REGION=${SPACES_REGION} \
                       --build-arg SPACES_CDN_DOMAIN=${SPACES_CDN_DOMAIN} \
                       -t sultan-prints-test .
          
          docker run -d -p 5000:8080 \
                     -e FLASK_ENV=${FLASK_ENV} \
                     -e SECRET_KEY=${SECRET_KEY} \
                     -e DATABASE_URL=${DATABASE_URL} \
                     -e ADMIN_EMAIL=${ADMIN_EMAIL} \
                     -e ADMIN_PASSWORD=${ADMIN_PASSWORD} \
                     -e SESSION_COOKIE_SECURE=${SESSION_COOKIE_SECURE} \
                     -e MAILERLITE_API_KEY=${MAILERLITE_API_KEY} \
                     -e MAIL_DEFAULT_SENDER=${MAIL_DEFAULT_SENDER} \
                     -e SPACES_KEY=${SPACES_KEY} \
                     -e SPACES_SECRET=${SPACES_SECRET} \
                     -e SPACES_BUCKET_NAME=${SPACES_BUCKET_NAME} \
                     -e SPACES_REGION=${SPACES_REGION} \
                     -e SPACES_CDN_DOMAIN=${SPACES_CDN_DOMAIN} \
                     --name test-app sultan-prints-test

      - name: Wait for app to be ready
        run: |
          echo "Waiting for app to start..."
          sleep 10 # Give it a generous fixed wait time to start
          for i in {1..30}; do
            if curl -s http://localhost:5000/ > /dev/null; then
              echo "App is up!"
              break
            fi
            echo "Attempt $i: App not ready yet. Waiting 2s..."
            sleep 2
          done
          # Final check
          curl -f -s http://localhost:5000/ > /dev/null || (echo "App failed to start" && docker logs test-app && exit 1)
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          playwright install
          
      - name: Run Playwright tests
        run: |
          cd tests_e2e
          pytest --html=report.html
      
      - name: Cleanup and show logs
        if: always()
        run: |
          echo "Dumping container logs for debugging..."
          docker logs test-app
          echo "Stopping container..."
          docker stop test-app
          docker rm test-app
          
      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: tests_e2e/report.html
          
      - name: Upload screenshots
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: screenshots
          path: tests_e2e/screenshots
